on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

env:
  AZURE_WEBAPP_NAME: kishanEcommBackend   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'
  CI: true 
  CONNECTION_URL: ${{ secrets.CONNECTION_URL }}   
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
  TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
  TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}              

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm ci
        npm run build --if-present
        npm run test --if-present
    